// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _webApiKey = String.fromEnvironment('FIREBASE_WEB_API_KEY');
  static const String _androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
  );
  static const String _iosApiKey = String.fromEnvironment('FIREBASE_IOS_API_KEY');
  static const String _macosApiKey = String.fromEnvironment(
    'FIREBASE_MACOS_API_KEY',
  );
  static const String _windowsApiKey = String.fromEnvironment(
    'FIREBASE_WINDOWS_API_KEY',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:774850821450:web:898c2d1ab7e531f4d415b3',
    messagingSenderId: '774850821450',
    projectId: 'ecommerceapp-8f3a3',
    authDomain: 'ecommerceapp-8f3a3.firebaseapp.com',
    storageBucket: 'ecommerceapp-8f3a3.firebasestorage.app',
    measurementId: 'G-H15HV7LQR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _androidApiKey,
    appId: '1:774850821450:android:bd0380cd5182a2f3d415b3',
    messagingSenderId: '774850821450',
    projectId: 'ecommerceapp-8f3a3',
    storageBucket: 'ecommerceapp-8f3a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _iosApiKey,
    appId: '1:774850821450:ios:6189136d605528c2d415b3',
    messagingSenderId: '774850821450',
    projectId: 'ecommerceapp-8f3a3',
    storageBucket: 'ecommerceapp-8f3a3.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _macosApiKey,
    appId: '1:774850821450:ios:6189136d605528c2d415b3',
    messagingSenderId: '774850821450',
    projectId: 'ecommerceapp-8f3a3',
    storageBucket: 'ecommerceapp-8f3a3.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _windowsApiKey,
    appId: '1:774850821450:web:2aa19582b5983357d415b3',
    messagingSenderId: '774850821450',
    projectId: 'ecommerceapp-8f3a3',
    authDomain: 'ecommerceapp-8f3a3.firebaseapp.com',
    storageBucket: 'ecommerceapp-8f3a3.firebasestorage.app',
    measurementId: 'G-696DCFE81S',
  );

}